DROP TABLE IF EXISTS CATEGORIE CASCADE;
DROP TABLE IF EXISTS FIXES CASCADE;
DROP TABLE IF EXISTS FLUX CASCADE;
DROP TABLE IF EXISTS PERIODE CASCADE;
DROP TABLE IF EXISTS TYPE_FLUX CASCADE;

DROP VIEW IF EXISTS vue_Periode CASCADE;
DROP VIEW IF EXISTS vue_Fixes CASCADE;
DROP VIEW IF EXISTS vue_Type_Flux CASCADE;
DROP VIEW IF EXISTS vue_Categorie CASCADE;
DROP VIEW IF EXISTS vue_Sous_Categorie CASCADE;

/*==============================================================*/
/* Table : CATEGORIE                                            */
/*==============================================================*/
create table CATEGORIE (
   ID_CATEGORIE         INT4                 not null,
   CAT_ID_CATEGORIE     INT4,
   NAME_CATEGORIE       VARCHAR(50)          null,
   constraint PK_CATEGORIE primary key (ID_CATEGORIE)
);

/*==============================================================*/
/* Table : FIXES                                                */
/*==============================================================*/
create table FIXES (
   ID_FIXES             INT4                 not null,
   NAME_FIXES           VARCHAR(20)          null,
   constraint PK_FIXES primary key (ID_FIXES)
);

/*==============================================================*/
/* Table : FLUX                                                 */
/*==============================================================*/
create table FLUX (
   ID_FLUX              INT4                 not null,
   ID_TYPE_FLUX         INT4                 not null,
   ID_PERIODE           INT4                 not null,
   ID_FIXES             INT4                 not null,
   ID_CATEGORIE         INT4                 null,
   DATE_FLUX            DATE                 null,
   MONTANT              DECIMAL(10,5)        null,
   DESCRIPTION          VARCHAR(1500)        null,
   TAGS                 VARCHAR(500)         null,
   constraint PK_FLUX primary key (ID_FLUX)
);

/*==============================================================*/
/* Table : PERIODE                                              */
/*==============================================================*/
create table PERIODE (
   ID_PERIODE           INT4                 not null,
   NAME_PERIODE          VARCHAR(20)          null,
   constraint PK_PERIODE primary key (ID_PERIODE)
);

/*==============================================================*/
/* Table : TYPE_FLUX                                            */
/*==============================================================*/
create table TYPE_FLUX (
   ID_TYPE_FLUX         INT4                 not null,
   NAME_TYPE_FLUX       VARCHAR(20)          null,
   constraint PK_TYPE_FLUX primary key (ID_TYPE_FLUX)
);

alter table CATEGORIE
   add constraint FK_CATEGORI_EST_ENFAN_CATEGORI foreign key (CAT_ID_CATEGORIE)
      references CATEGORIE (ID_CATEGORIE)
      on delete restrict on update restrict;

alter table FLUX
   add constraint FK_FLUX_CATEGORIS_CATEGORI foreign key (ID_CATEGORIE)
      references CATEGORIE (ID_CATEGORIE)
      on delete restrict on update restrict;

alter table FLUX
   add constraint FK_FLUX_EST_FIXES foreign key (ID_FIXES)
      references FIXES (ID_FIXES)
      on delete restrict on update restrict;

alter table FLUX
   add constraint FK_FLUX_EST_DE_TY_TYPE_FLU foreign key (ID_TYPE_FLUX)
      references TYPE_FLUX (ID_TYPE_FLUX)
      on delete restrict on update restrict;

alter table FLUX
   add constraint FK_FLUX_SE_PASSE_PERIODE foreign key (ID_PERIODE)
      references PERIODE (ID_PERIODE)
      on delete restrict on update restrict;

/*==============================================================*/
/* CREATE VIEWS                                                 */
/*==============================================================*/

CREATE OR REPLACE VIEW vue_Periode AS
   SELECT ID_PERIODE AS "ID Periode", NAME_PERIODE as "Periode"
   FROM PERIODE;

CREATE OR REPLACE VIEW vue_Fixes AS
   SELECT ID_FIXES AS "ID Fixes", NAME_FIXES as "Fixes"
   FROM FIXES;

CREATE OR REPLACE VIEW vue_Type_Flux AS
   SELECT ID_TYPE_FLUX AS "ID Type Flux", NAME_TYPE_FLUX AS "Type Flux"
   FROM TYPE_FLUX;

CREATE OR REPLACE VIEW vue_Categorie AS
   SELECT ID_CATEGORIE AS "ID Categorie", NAME_CATEGORIE AS "Categorie"
   FROM CATEGORIE
   WHERE CAT_ID_CATEGORIE IS NULL;

CREATE OR REPLACE VIEW vue_Sous_Categorie AS
   SELECT c1.ID_CATEGORIE AS "ID Categorie", c2.NAME_CATEGORIE AS "Categorie", c1.NAME_CATEGORIE AS "Sous-Categorie"
   FROM CATEGORIE c1
      JOIN CATEGORIE c2 ON c1.CAT_ID_CATEGORIE = c2.ID_CATEGORIE
   WHERE c1.CAT_ID_CATEGORIE IS NOT NULL;


/*==============================================================*/
/* INSERT DATA                                                  */
/*==============================================================*/

INSERT INTO FIXES(ID_FIXES, NAME_FIXES) VALUES (1, 'Fixe');
INSERT INTO FIXES(ID_FIXES, NAME_FIXES) VALUES (2, 'Variable');


INSERT INTO TYPE_FLUX(ID_TYPE_FLUX, NAME_TYPE_FLUX) VALUES (1, 'Entrée');
INSERT INTO TYPE_FLUX(ID_TYPE_FLUX, NAME_TYPE_FLUX) VALUES (2, 'Sortie');
INSERT INTO TYPE_FLUX(ID_TYPE_FLUX, NAME_TYPE_FLUX) VALUES (3, 'Neutre');
INSERT INTO TYPE_FLUX(ID_TYPE_FLUX, NAME_TYPE_FLUX) VALUES (4, 'Réparation');

INSERT INTO PERIODE(ID_PERIODE, NAME_PERIODE) VALUES (1, 'Entreprise');
INSERT INTO PERIODE(ID_PERIODE, NAME_PERIODE) VALUES (2, 'Ecole');
INSERT INTO PERIODE(ID_PERIODE, NAME_PERIODE) VALUES (3, 'Vacances');

INSERT INTO CATEGORIE(ID_CATEGORIE, NAME_CATEGORIE) VALUES (1, 'Courses');
INSERT INTO CATEGORIE(ID_CATEGORIE, NAME_CATEGORIE) VALUES (2, 'Mode');
INSERT INTO CATEGORIE(ID_CATEGORIE, NAME_CATEGORIE) VALUES (3, 'Esthétique');
INSERT INTO CATEGORIE(ID_CATEGORIE, NAME_CATEGORIE) VALUES (4, 'Hygiène');
INSERT INTO CATEGORIE(ID_CATEGORIE, NAME_CATEGORIE) VALUES (5, 'Abonnement');
INSERT INTO CATEGORIE(ID_CATEGORIE, NAME_CATEGORIE) VALUES (6, 'Transports');
INSERT INTO CATEGORIE(ID_CATEGORIE, NAME_CATEGORIE) VALUES (7, 'Logement');
INSERT INTO CATEGORIE(ID_CATEGORIE, NAME_CATEGORIE) VALUES (8, 'Aide');
INSERT INTO CATEGORIE(ID_CATEGORIE, NAME_CATEGORIE) VALUES (9, 'Divertissement');
INSERT INTO CATEGORIE(ID_CATEGORIE, NAME_CATEGORIE) VALUES (10, 'Emprunt');
INSERT INTO CATEGORIE(ID_CATEGORIE, NAME_CATEGORIE) VALUES (11, 'Emploi');
INSERT INTO CATEGORIE(ID_CATEGORIE, NAME_CATEGORIE) VALUES (12, 'Epargne');
INSERT INTO CATEGORIE(ID_CATEGORIE, NAME_CATEGORIE) VALUES (13, 'Impôts');
INSERT INTO CATEGORIE(ID_CATEGORIE, NAME_CATEGORIE) VALUES (14, 'Santé');
INSERT INTO CATEGORIE(ID_CATEGORIE, NAME_CATEGORIE) VALUES (15, 'Tech');
INSERT INTO CATEGORIE(ID_CATEGORIE, NAME_CATEGORIE) VALUES (16, 'Autre');
INSERT INTO CATEGORIE(ID_CATEGORIE, CAT_ID_CATEGORIE, NAME_CATEGORIE) VALUES (17, 1, 'Viandes');
INSERT INTO CATEGORIE(ID_CATEGORIE, CAT_ID_CATEGORIE, NAME_CATEGORIE) VALUES (18, 1, 'Fromages');
INSERT INTO CATEGORIE(ID_CATEGORIE, CAT_ID_CATEGORIE, NAME_CATEGORIE) VALUES (19, 1, 'Légumes');
INSERT INTO CATEGORIE(ID_CATEGORIE, CAT_ID_CATEGORIE, NAME_CATEGORIE) VALUES (20, 1, 'Fruits');
INSERT INTO CATEGORIE(ID_CATEGORIE, CAT_ID_CATEGORIE, NAME_CATEGORIE) VALUES (21, 1, 'Sauces');
INSERT INTO CATEGORIE(ID_CATEGORIE, CAT_ID_CATEGORIE, NAME_CATEGORIE) VALUES (22, 1, 'Café');
INSERT INTO CATEGORIE(ID_CATEGORIE, CAT_ID_CATEGORIE, NAME_CATEGORIE) VALUES (23, 1, 'Sucrerie');
INSERT INTO CATEGORIE(ID_CATEGORIE, CAT_ID_CATEGORIE, NAME_CATEGORIE) VALUES (24, 1, 'Pain');
INSERT INTO CATEGORIE(ID_CATEGORIE, CAT_ID_CATEGORIE, NAME_CATEGORIE) VALUES (25, 1, 'Desserts');
INSERT INTO CATEGORIE(ID_CATEGORIE, CAT_ID_CATEGORIE, NAME_CATEGORIE) VALUES (26, 1, 'Féculents');
INSERT INTO CATEGORIE(ID_CATEGORIE, CAT_ID_CATEGORIE, NAME_CATEGORIE) VALUES (27, 1, 'Epices');
INSERT INTO CATEGORIE(ID_CATEGORIE, CAT_ID_CATEGORIE, NAME_CATEGORIE) VALUES (28, 1, 'Apéritifs');
INSERT INTO CATEGORIE(ID_CATEGORIE, CAT_ID_CATEGORIE, NAME_CATEGORIE) VALUES (29, 1, 'Soda');
INSERT INTO CATEGORIE(ID_CATEGORIE, CAT_ID_CATEGORIE, NAME_CATEGORIE) VALUES (30, 1, 'Alcool');
INSERT INTO CATEGORIE(ID_CATEGORIE, CAT_ID_CATEGORIE, NAME_CATEGORIE) VALUES (31, 1, 'Jus');
INSERT INTO CATEGORIE(ID_CATEGORIE, CAT_ID_CATEGORIE, NAME_CATEGORIE) VALUES (32, 1, 'Sirop');
INSERT INTO CATEGORIE(ID_CATEGORIE, CAT_ID_CATEGORIE, NAME_CATEGORIE) VALUES (33, 1, 'Lait');
INSERT INTO CATEGORIE(ID_CATEGORIE, CAT_ID_CATEGORIE, NAME_CATEGORIE) VALUES (34, 2, 'Haut');
INSERT INTO CATEGORIE(ID_CATEGORIE, CAT_ID_CATEGORIE, NAME_CATEGORIE) VALUES (35, 2, 'T-shirt');
INSERT INTO CATEGORIE(ID_CATEGORIE, CAT_ID_CATEGORIE, NAME_CATEGORIE) VALUES (36, 2, 'Bas');
INSERT INTO CATEGORIE(ID_CATEGORIE, CAT_ID_CATEGORIE, NAME_CATEGORIE) VALUES (37, 2, 'Sous-Vêtements');
INSERT INTO CATEGORIE(ID_CATEGORIE, CAT_ID_CATEGORIE, NAME_CATEGORIE) VALUES (38, 2, 'Chaussures');
INSERT INTO CATEGORIE(ID_CATEGORIE, CAT_ID_CATEGORIE, NAME_CATEGORIE) VALUES (39, 2, 'Chaussettes');
INSERT INTO CATEGORIE(ID_CATEGORIE, CAT_ID_CATEGORIE, NAME_CATEGORIE) VALUES (40, 2, 'Accessoires');
INSERT INTO CATEGORIE(ID_CATEGORIE, CAT_ID_CATEGORIE, NAME_CATEGORIE) VALUES (41, 2, 'Pyjama');
INSERT INTO CATEGORIE(ID_CATEGORIE, CAT_ID_CATEGORIE, NAME_CATEGORIE) VALUES (42, 3, 'Shampoing');
INSERT INTO CATEGORIE(ID_CATEGORIE, CAT_ID_CATEGORIE, NAME_CATEGORIE) VALUES (43, 3, 'Gel');
INSERT INTO CATEGORIE(ID_CATEGORIE, CAT_ID_CATEGORIE, NAME_CATEGORIE) VALUES (44, 3, 'Visage');
INSERT INTO CATEGORIE(ID_CATEGORIE, CAT_ID_CATEGORIE, NAME_CATEGORIE) VALUES (45, 3, 'Dentaire');
INSERT INTO CATEGORIE(ID_CATEGORIE, CAT_ID_CATEGORIE, NAME_CATEGORIE) VALUES (46, 3, 'Crème');
INSERT INTO CATEGORIE(ID_CATEGORIE, CAT_ID_CATEGORIE, NAME_CATEGORIE) VALUES (47, 3, 'Coiffeur');
INSERT INTO CATEGORIE(ID_CATEGORIE, CAT_ID_CATEGORIE, NAME_CATEGORIE) VALUES (48, 3, 'Savon');
INSERT INTO CATEGORIE(ID_CATEGORIE, CAT_ID_CATEGORIE, NAME_CATEGORIE) VALUES (49, 3, 'Lessive');
INSERT INTO CATEGORIE(ID_CATEGORIE, CAT_ID_CATEGORIE, NAME_CATEGORIE) VALUES (50, 3, 'Vaisselle');
INSERT INTO CATEGORIE(ID_CATEGORIE, CAT_ID_CATEGORIE, NAME_CATEGORIE) VALUES (51, 3, 'Ménage');
INSERT INTO CATEGORIE(ID_CATEGORIE, CAT_ID_CATEGORIE, NAME_CATEGORIE) VALUES (52, 3, 'Sanitaire');
INSERT INTO CATEGORIE(ID_CATEGORIE, CAT_ID_CATEGORIE, NAME_CATEGORIE) VALUES (53, 3, 'Oreiller');
INSERT INTO CATEGORIE(ID_CATEGORIE, CAT_ID_CATEGORIE, NAME_CATEGORIE) VALUES (54, 3, 'Taies oreiller');
INSERT INTO CATEGORIE(ID_CATEGORIE, CAT_ID_CATEGORIE, NAME_CATEGORIE) VALUES (55, 3, 'Couette');
INSERT INTO CATEGORIE(ID_CATEGORIE, CAT_ID_CATEGORIE, NAME_CATEGORIE) VALUES (56, 3, 'Housse de couette');
INSERT INTO CATEGORIE(ID_CATEGORIE, CAT_ID_CATEGORIE, NAME_CATEGORIE) VALUES (57, 3, 'Drap Housse');
INSERT INTO CATEGORIE(ID_CATEGORIE, CAT_ID_CATEGORIE, NAME_CATEGORIE) VALUES (58, 3, 'Protège Oreiller');
INSERT INTO CATEGORIE(ID_CATEGORIE, CAT_ID_CATEGORIE, NAME_CATEGORIE) VALUES (59, 3, 'Protège Matelas');
INSERT INTO CATEGORIE(ID_CATEGORIE, CAT_ID_CATEGORIE, NAME_CATEGORIE) VALUES (60, 4, 'Streaming');
INSERT INTO CATEGORIE(ID_CATEGORIE, CAT_ID_CATEGORIE, NAME_CATEGORIE) VALUES (61, 4, 'Sports');
INSERT INTO CATEGORIE(ID_CATEGORIE, CAT_ID_CATEGORIE, NAME_CATEGORIE) VALUES (62, 4, 'Internet');
INSERT INTO CATEGORIE(ID_CATEGORIE, CAT_ID_CATEGORIE, NAME_CATEGORIE) VALUES (63, 4, 'Mobile');
INSERT INTO CATEGORIE(ID_CATEGORIE, CAT_ID_CATEGORIE, NAME_CATEGORIE) VALUES (64, 5, 'Carburant');
INSERT INTO CATEGORIE(ID_CATEGORIE, CAT_ID_CATEGORIE, NAME_CATEGORIE) VALUES (65, 5, 'Huile Moteur');
INSERT INTO CATEGORIE(ID_CATEGORIE, CAT_ID_CATEGORIE, NAME_CATEGORIE) VALUES (66, 5, 'Assurance véhicule');
INSERT INTO CATEGORIE(ID_CATEGORIE, CAT_ID_CATEGORIE, NAME_CATEGORIE) VALUES (67, 5, 'Garage');
INSERT INTO CATEGORIE(ID_CATEGORIE, CAT_ID_CATEGORIE, NAME_CATEGORIE) VALUES (68, 5, 'Entretien véhicule');
INSERT INTO CATEGORIE(ID_CATEGORIE, CAT_ID_CATEGORIE, NAME_CATEGORIE) VALUES (69, 5, 'Autoroute');
INSERT INTO CATEGORIE(ID_CATEGORIE, CAT_ID_CATEGORIE, NAME_CATEGORIE) VALUES (70, 5, 'Bus');
INSERT INTO CATEGORIE(ID_CATEGORIE, CAT_ID_CATEGORIE, NAME_CATEGORIE) VALUES (71, 5, 'Tram');
INSERT INTO CATEGORIE(ID_CATEGORIE, CAT_ID_CATEGORIE, NAME_CATEGORIE) VALUES (72, 5, 'Train');
INSERT INTO CATEGORIE(ID_CATEGORIE, CAT_ID_CATEGORIE, NAME_CATEGORIE) VALUES (73, 5, 'Avion');
INSERT INTO CATEGORIE(ID_CATEGORIE, CAT_ID_CATEGORIE, NAME_CATEGORIE) VALUES (74, 5, 'Covoiturage');
INSERT INTO CATEGORIE(ID_CATEGORIE, CAT_ID_CATEGORIE, NAME_CATEGORIE) VALUES (75, 5, 'Parking');
INSERT INTO CATEGORIE(ID_CATEGORIE, CAT_ID_CATEGORIE, NAME_CATEGORIE) VALUES (76, 6, 'Loyer');
INSERT INTO CATEGORIE(ID_CATEGORIE, CAT_ID_CATEGORIE, NAME_CATEGORIE) VALUES (77, 6, 'Eau');
INSERT INTO CATEGORIE(ID_CATEGORIE, CAT_ID_CATEGORIE, NAME_CATEGORIE) VALUES (78, 6, 'Electricité');
INSERT INTO CATEGORIE(ID_CATEGORIE, CAT_ID_CATEGORIE, NAME_CATEGORIE) VALUES (79, 6, 'Chauffage');
INSERT INTO CATEGORIE(ID_CATEGORIE, CAT_ID_CATEGORIE, NAME_CATEGORIE) VALUES (80, 6, 'Assurance logement');
INSERT INTO CATEGORIE(ID_CATEGORIE, CAT_ID_CATEGORIE, NAME_CATEGORIE) VALUES (81, 6, 'Copropriété');
INSERT INTO CATEGORIE(ID_CATEGORIE, CAT_ID_CATEGORIE, NAME_CATEGORIE) VALUES (82, 7, 'APL');
INSERT INTO CATEGORIE(ID_CATEGORIE, CAT_ID_CATEGORIE, NAME_CATEGORIE) VALUES (83, 7, 'Mobili-Jeune');
INSERT INTO CATEGORIE(ID_CATEGORIE, CAT_ID_CATEGORIE, NAME_CATEGORIE) VALUES (84, 8, 'Cinéma');
INSERT INTO CATEGORIE(ID_CATEGORIE, CAT_ID_CATEGORIE, NAME_CATEGORIE) VALUES (85, 8, 'Restauration');
INSERT INTO CATEGORIE(ID_CATEGORIE, CAT_ID_CATEGORIE, NAME_CATEGORIE) VALUES (86, 8, 'Brasserie');
INSERT INTO CATEGORIE(ID_CATEGORIE, CAT_ID_CATEGORIE, NAME_CATEGORIE) VALUES (87, 8, 'Vacances');
INSERT INTO CATEGORIE(ID_CATEGORIE, CAT_ID_CATEGORIE, NAME_CATEGORIE) VALUES (88, 8, 'Jeux-vidéos');
INSERT INTO CATEGORIE(ID_CATEGORIE, CAT_ID_CATEGORIE, NAME_CATEGORIE) VALUES (89, 8, 'Informatique');
INSERT INTO CATEGORIE(ID_CATEGORIE, CAT_ID_CATEGORIE, NAME_CATEGORIE) VALUES (90, 9, 'Famille');
INSERT INTO CATEGORIE(ID_CATEGORIE, CAT_ID_CATEGORIE, NAME_CATEGORIE) VALUES (91, 9, 'Ami');
INSERT INTO CATEGORIE(ID_CATEGORIE, CAT_ID_CATEGORIE, NAME_CATEGORIE) VALUES (92, 9, 'Bancaire');
INSERT INTO CATEGORIE(ID_CATEGORIE, CAT_ID_CATEGORIE, NAME_CATEGORIE) VALUES (93, 10, 'Salaire');
INSERT INTO CATEGORIE(ID_CATEGORIE, CAT_ID_CATEGORIE, NAME_CATEGORIE) VALUES (94, 10, 'Primes');
INSERT INTO CATEGORIE(ID_CATEGORIE, CAT_ID_CATEGORIE, NAME_CATEGORIE) VALUES (95, 10, 'Chèques cadeaux');
INSERT INTO CATEGORIE(ID_CATEGORIE, CAT_ID_CATEGORIE, NAME_CATEGORIE) VALUES (96, 10, 'Chèques vacances');
INSERT INTO CATEGORIE(ID_CATEGORIE, CAT_ID_CATEGORIE, NAME_CATEGORIE) VALUES (97, 11, 'Epargne');
INSERT INTO CATEGORIE(ID_CATEGORIE, CAT_ID_CATEGORIE, NAME_CATEGORIE) VALUES (98, 12, 'Impôts');
INSERT INTO CATEGORIE(ID_CATEGORIE, CAT_ID_CATEGORIE, NAME_CATEGORIE) VALUES (99, 13, 'Santé');
INSERT INTO CATEGORIE(ID_CATEGORIE, CAT_ID_CATEGORIE, NAME_CATEGORIE) VALUES (100, 14, 'Tech');
INSERT INTO CATEGORIE(ID_CATEGORIE, CAT_ID_CATEGORIE, NAME_CATEGORIE) VALUES (101, 15, 'Autre');

